# Generated by Django 2.1.1 on 2019-01-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Sabzi',
        ),
        migrations.RenameField(
            model_name='sabzi',
            old_name='item',
            new_name='sabzi',
        ),
        migrations.RenameField(
            model_name='sabzi',
            old_name='item_image',
            new_name='sabzi_image',
        ),
    ]
