# Generated by Django 2.1.1 on 2019-01-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20190105_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beverages', models.CharField(max_length=50)),
                ('beverages_image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Breads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breads', models.CharField(max_length=50)),
                ('breads_image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Desserts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desserts', models.CharField(max_length=50)),
                ('desserts_image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snacks', models.CharField(max_length=50)),
                ('snacks_image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StreetFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetfood', models.CharField(max_length=50)),
                ('streetfood_image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Thali',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thali', models.CharField(max_length=50)),
                ('thali_image', models.FileField(upload_to='')),
            ],
        ),
    ]
