# Generated by Django 2.1.1 on 2019-01-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_beverages_breads_desserts_snacks_streetfood_thali'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rice', models.CharField(max_length=50)),
                ('rice_image', models.FileField(upload_to='')),
            ],
        ),
    ]
