# Generated by Django 2.1.1 on 2019-01-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rice'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='amount',
            field=models.FloatField(default=10),
        ),
    ]
