# Generated by Django 2.1.4 on 2019-01-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20190106_1223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sabzi',
            new_name='Vegetable',
        ),
        migrations.RenameField(
            model_name='vegetable',
            old_name='sabzi',
            new_name='vegetable',
        ),
        migrations.RenameField(
            model_name='vegetable',
            old_name='sabzi_amt',
            new_name='vegetable_amt',
        ),
        migrations.RenameField(
            model_name='vegetable',
            old_name='sabzi_image',
            new_name='vegetable_image',
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
