# Generated by Django 2.1.4 on 2019-01-12 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20190108_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 12, 22, 0, 56, 466566)),
        ),
    ]
