# Generated by Django 2.1.4 on 2019-01-12 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_menu_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 12, 22, 5, 27, 73933)),
        ),
    ]
