# Generated by Django 2.1.4 on 2019-01-12 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20190112_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 12, 22, 10, 27, 465291)),
        ),
    ]
