# Generated by Django 2.1.4 on 2019-01-12 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_auto_20190112_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 12, 22, 11, 4, 402398)),
        ),
    ]
