# Generated by Django 2.1.4 on 2019-01-12 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_auto_20190112_2211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thali',
            new_name='Plate',
        ),
        migrations.RenameField(
            model_name='plate',
            old_name='thali',
            new_name='plate',
        ),
        migrations.RenameField(
            model_name='plate',
            old_name='thali_amt',
            new_name='plate_amt',
        ),
        migrations.RenameField(
            model_name='plate',
            old_name='thali_image',
            new_name='plate_image',
        ),
        migrations.AlterField(
            model_name='menu',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 12, 22, 27, 59, 966340)),
        ),
    ]
